# Generated by Django 5.2.4 on 2026-06-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatamailerContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=320)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('preference_key', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['email'], name='dm_events_email_idx'), models.Index(fields=['event_type', 'created_at'], name='dm_events_type_created_idx')],
            },
        ),
    ]
