# Generated by Django 5.2.4 on 2026-06-26 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_datamaileroutboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatamailerOutboxDispatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('acked_count', models.PositiveIntegerField(default=0)),
                ('retrying_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='dm_outbox_run_status_idx')],
            },
        ),
    ]
