# Generated by Django 5.2.4 on 2026-06-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_datamaileroutboxdispatchrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamailercontactevent',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datamailercontactevent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
