# Generated by Django 5.2.4 on 2026-06-26 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_datamailercontactevent_duplicate_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatamailerSendAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('transactional', 'Transactional'), ('recipient_list', 'Recipient list'), ('transient_recipient_list', 'Transient recipient list')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('template_key', models.CharField(blank=True, max_length=120)),
                ('category_tag', models.CharField(blank=True, max_length=80)),
                ('list_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('event', models.CharField(blank=True, max_length=120)),
                ('intended_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('enqueued_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('idempotent_replay_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='dm_send_status_occurred_idx'), models.Index(fields=['category_tag', 'occurred_at'], name='dm_send_category_occurred_idx'), models.Index(fields=['event', 'occurred_at'], name='dm_send_event_occurred_idx')],
                'constraints': [models.UniqueConstraint(fields=('send_type', 'idempotency_key'), name='dm_send_audit_type_idem_uniq')],
            },
        ),
    ]
