plan:
	terraform plan -var-file=env.json -var="environment=dev"

apply:
	terraform apply -var-file=env.json -var="environment=dev"

plan_prod:
	terraform plan -var-file=env.json -var="environment=prod"

apply_prod:
	terraform apply -var-file=env.json -var="environment=prod"
