from .enums import CONTENT_ENUM_SCHEMAS
from .homeworks import HOMEWORK_SCHEMAS
from .projects import PROJECT_SCHEMAS
from .questions import QUESTION_SCHEMAS


CONTENT_SCHEMAS = {}
CONTENT_SCHEMAS.update(HOMEWORK_SCHEMAS)
CONTENT_SCHEMAS.update(PROJECT_SCHEMAS)
CONTENT_SCHEMAS.update(QUESTION_SCHEMAS)
CONTENT_SCHEMAS.update(CONTENT_ENUM_SCHEMAS)
