# Generated by Django 5.1.7 on 2025-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certificate_name',
            field=models.CharField(blank=True, help_text='Your actual name that will appear on your certificates', max_length=255, null=True, verbose_name='Certificate name'),
        ),
    ]
