# Generated by Django 5.2.4 on 2025-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode theme', verbose_name='Dark mode'),
        ),
    ]
