# Generated by Django 5.2.4 on 2026-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_certificate_name_from_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_role',
            field=models.CharField(blank=True, help_text='Role last used on a course registration form', max_length=40, verbose_name='Registration role'),
        ),
    ]
