# Generated by Django 5.2.4 on 2026-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_country_customuser_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_deadline_reminders',
            field=models.BooleanField(default=True, help_text='Receive reminder emails when homework or peer review deadlines are within 24 hours and you have not submitted, plus project reminders one week before and one day before the deadline when you have not submitted. Peer review reminders are sent when assigned reviews are unfinished.', verbose_name='Deadline reminders'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_submission_confirmations',
            field=models.BooleanField(default=True, help_text='Receive homework and project submission emails with a copy of submitted results.', verbose_name='Submission confirmations'),
        ),
    ]
