# Generated by Django 5.2.4 on 2026-06-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_email_deadline_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_course_updates',
            field=models.BooleanField(default=True, help_text='Receive general course and workshop emails, such as course start announcements and workshop start announcements.', verbose_name='General course-related emails'),
        ),
    ]
