# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_email_course_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "IANA timezone used for backend-rendered deadlines and "
                    "notification emails."
                ),
                max_length=100,
                verbose_name="Preferred timezone",
            ),
        ),
    ]
