# Generated by Django 5.2.4 on 2026-06-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_preferred_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_course_updates',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_deadline_reminders',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_submission_confirmations',
        ),
    ]
