from .content_paths.registry import CONTENT_PATHS_BY_URL_NAME
from .course_paths import COURSE_PATHS_BY_URL_NAME
from .data_paths import DATA_PATHS_BY_URL_NAME


PATHS_BY_URL_NAME = {}
PATHS_BY_URL_NAME.update(DATA_PATHS_BY_URL_NAME)
PATHS_BY_URL_NAME.update(COURSE_PATHS_BY_URL_NAME)
PATHS_BY_URL_NAME.update(CONTENT_PATHS_BY_URL_NAME)
