# Generated by Django 4.2 on 2023-12-23 21:37

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (courses.models.AnswerTypes["ANY"], "Any"),
                    (courses.models.AnswerTypes["FLOAT"], "Float"),
                    (courses.models.AnswerTypes["INTEGER"], "Integer"),
                    (courses.models.AnswerTypes["EXACT_STRING"], "Exact String"),
                    (courses.models.AnswerTypes["CONTAINS_STRING"], "Contains String"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
