# Generated by Django 4.2.9 on 2024-01-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
