# Generated by Django 4.2 on 2023-12-26 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_enrollment_certificate_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="faq_contribution_field",
            field=models.BooleanField(
                default=True, help_text="Include field for FAQ contributions"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="learning_in_public_cap",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="homework",
            name="problems_comments_field",
            field=models.BooleanField(
                default=True, help_text="Include field for problems and comments"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="time_spent_homework_field",
            field=models.BooleanField(
                default=True, help_text="Include field for time spent on homework"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="time_spent_lectures_field",
            field=models.BooleanField(
                default=True, help_text="Include field for time spent on lectures"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="faq_contribution",
            field=models.TextField(blank=True, help_text="Contribution to FAQ"),
        ),
        migrations.AddField(
            model_name="submission",
            name="homework_link",
            field=models.URLField(
                default="https://google.com",
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "git"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="learning_in_public_links",
            field=models.JSONField(
                blank=True,
                help_text="Links where students talk about the course",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="problems_comments",
            field=models.TextField(
                blank=True, help_text="Any problems, comments, or feedback"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="time_spent_homework",
            field=models.FloatField(
                blank=True, help_text="Time spent on homework (in hours)", null=True
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="time_spent_lectures",
            field=models.FloatField(
                blank=True,
                help_text="Time spent on lectures and reading (in hours)",
                null=True,
            ),
        ),
    ]
