# Generated by Django 4.2.9 on 2024-01-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_projectsubmission_submitted_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
    ]
