# Generated by Django 4.2.9 on 2024-02-06 21:07

from django.db import migrations

def replace_commas_with_linebreaks(apps, schema_editor):
    Question = apps.get_model('courses', 'Question')
    for question in Question.objects.all():
        if question.possible_answers:
            question.possible_answers = question.possible_answers.replace(',', '\n')
            question.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_student'),
    ]

    operations = [
        migrations.RunPython(replace_commas_with_linebreaks),
    ]
