# Generated by Django 4.2 on 2023-12-19 19:22

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_homework_is_scored_submission_answer_submission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="submitted_on",
        ),
        migrations.AddField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    (courses.models.AnswerTypes["ANY"], "Any"),
                    (courses.models.AnswerTypes["FLOAT"], "Float"),
                    (courses.models.AnswerTypes["INTEGER"], "Integer"),
                    (courses.models.AnswerTypes["EXACT_STRING"], "Exact String"),
                    (courses.models.AnswerTypes["CONTAINS_STRING"], "Contains String"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    (
                        courses.models.QuestionTypes["MULTIPLE_CHOICE"],
                        "Multiple Choice",
                    ),
                    (courses.models.QuestionTypes["FREE_FORM"], "Free Form"),
                    (courses.models.QuestionTypes["CHECKBOXES"], "Checkboxes"),
                ],
                max_length=2,
            ),
        ),
    ]
