# Generated by Django 4.2 on 2024-01-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_homework_faq_contribution_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="homework_url_field",
            field=models.BooleanField(
                default=True, help_text="Include field for homework URL"
            ),
        ),
    ]
