# Generated by Django 4.2.9 on 2024-01-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_rename_name_project_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
