# Generated by Django 4.2 on 2024-01-03 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_homework_homework_url_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="homework_link",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "git"]
                    )
                ],
            ),
        ),
    ]
