# Generated by Django 4.2 on 2024-01-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_submission_homework_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
