# Generated by Django 4.2 on 2024-01-04 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_answer_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="faq_document_url",
            field=models.URLField(
                blank=True,
                help_text="The URL of the FAQ document for the course.",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="social_media_hashtag",
            field=models.CharField(
                blank=True,
                help_text="The hashtag associated with the course for social media use.",
                max_length=100,
            ),
        ),
    ]
