# Generated by Django 4.2.9 on 2024-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_remove_projectsubmission_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="faq_contribution_field",
            field=models.BooleanField(
                default=True, help_text="Include field for FAQ contributions"
            ),
        ),
    ]
