# Generated by Django 4.2.10 on 2024-02-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_enrollment_position_on_leaderboard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="student",
        ),
    ]
