# Generated by Django 4.2 on 2024-01-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_course_faq_document_url_course_social_media_hashtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="faq_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="learning_in_public_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="questions_score",
            field=models.IntegerField(default=0),
        ),
    ]
