# Generated by Django 4.2 on 2024-01-07 12:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0008_submission_faq_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("submission_due_date", models.DateTimeField()),
                ("learning_in_public_cap_project", models.IntegerField(default=14)),
                ("peer_review_due_date", models.DateTimeField()),
                ("learning_in_public_cap_review", models.IntegerField(default=2)),
                ("number_of_peers_to_evaluate", models.IntegerField(default=3)),
                ("points_to_pass", models.IntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CS", "COLLECTING_SUBMISSIONS"),
                            ("PR", "PEER_REVIEWING"),
                            ("CO", "COMPLETED"),
                        ],
                        default="CS",
                        max_length=2,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("max_score", models.IntegerField(default=4)),
                (
                    "review_criteria_type",
                    models.CharField(
                        choices=[("RB", "Radio Buttons"), ("CB", "Checkboxes")],
                        max_length=2,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_link",
                    models.URLField(validators=[django.core.validators.URLValidator()]),
                ),
                ("commit_id", models.CharField(max_length=40)),
                ("learning_in_public_links", models.JSONField(blank=True, null=True)),
                ("faq_contribution", models.TextField(blank=True)),
                ("time_spent", models.FloatField()),
                ("comment", models.TextField(blank=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.enrollment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_to_peer", models.TextField()),
                ("learning_in_public_links", models.JSONField(blank=True, null=True)),
                ("time_spent_reviewing", models.FloatField()),
                ("comments", models.TextField(blank=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission_under_evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.projectsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CriteriaResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.reviewcriteria",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria_responses",
                        to="courses.peerreview",
                    ),
                ),
            ],
        ),
    ]
