# Generated by Django 4.2.10 on 2024-02-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_remove_answer_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerreview",
            name="optional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="state",
            field=models.CharField(
                choices=[("TR", "TO_REVIEW"), ("SU", "SUBMITTED")],
                default="TR",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="peerreview",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="peerreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewers",
                to="courses.projectsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="peerreview",
            name="submission_under_evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_under_evaluation",
                to="courses.projectsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="peerreview",
            name="time_spent_reviewing",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectsubmission",
            name="time_spent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
