# Generated by Django 4.2.10 on 2024-03-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_rename_comments_peerreview_problems_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewcriteria",
            name="max_score",
        ),
    ]
