# Generated by Django 4.2.11 on 2024-03-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_remove_reviewcriteria_max_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="position_on_leaderboard",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
