# Generated by Django 4.2.11 on 2024-04-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_alter_enrollment_position_on_leaderboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="points_for_peer_review",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="peer_review_faq_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="peer_review_learning_in_public_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="peer_review_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="project_faq_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="project_learning_in_public_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="project_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="reviewed_enough_peers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectsubmission",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProjectEvaluationScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "review_criteria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.reviewcriteria",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.projectsubmission",
                    ),
                ),
            ],
        ),
    ]
