# Generated by Django 4.2.11 on 2024-04-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_project_points_for_peer_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsubmission",
            name="peer_review_faq_score",
        ),
    ]
