# Generated by Django 4.2.14 on 2024-07-31 05:05

import courses.validators.custom_url_validators
import courses.validators.validating_json_field
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_homework_is_scored_homework_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='github_link',
            field=models.URLField(validators=[django.core.validators.URLValidator(), courses.validators.custom_url_validators.validate_url_200]),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='learning_in_public_links',
            field=courses.validators.validating_json_field.ValidatingJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='homework_link',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'git']), courses.validators.custom_url_validators.validate_url_200]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='learning_in_public_links',
            field=courses.validators.validating_json_field.ValidatingJSONField(blank=True, help_text='Links where students talk about the course', null=True),
        ),
    ]
