# Generated by Django 4.2.14 on 2024-10-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_enrollment_about_me_enrollment_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='learning_in_public_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='learning_in_public_links',
            field=models.JSONField(blank=True, help_text='Links where students talk about the course', null=True),
        ),
        migrations.CreateModel(
            name='HomeworkStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.IntegerField(default=0)),
                ('min_questions_score', models.IntegerField(blank=True, null=True)),
                ('max_questions_score', models.IntegerField(blank=True, null=True)),
                ('avg_questions_score', models.FloatField(blank=True, null=True)),
                ('median_questions_score', models.FloatField(blank=True, null=True)),
                ('q1_questions_score', models.FloatField(blank=True, null=True)),
                ('q3_questions_score', models.FloatField(blank=True, null=True)),
                ('min_total_score', models.IntegerField(blank=True, null=True)),
                ('max_total_score', models.IntegerField(blank=True, null=True)),
                ('avg_total_score', models.FloatField(blank=True, null=True)),
                ('median_total_score', models.FloatField(blank=True, null=True)),
                ('q1_total_score', models.FloatField(blank=True, null=True)),
                ('q3_total_score', models.FloatField(blank=True, null=True)),
                ('min_learning_in_public_score', models.IntegerField(blank=True, null=True)),
                ('max_learning_in_public_score', models.IntegerField(blank=True, null=True)),
                ('avg_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('median_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('q1_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('q3_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('min_time_spent_lectures', models.FloatField(blank=True, null=True)),
                ('max_time_spent_lectures', models.FloatField(blank=True, null=True)),
                ('avg_time_spent_lectures', models.FloatField(blank=True, null=True)),
                ('median_time_spent_lectures', models.FloatField(blank=True, null=True)),
                ('q1_time_spent_lectures', models.FloatField(blank=True, null=True)),
                ('q3_time_spent_lectures', models.FloatField(blank=True, null=True)),
                ('min_time_spent_homework', models.FloatField(blank=True, null=True)),
                ('max_time_spent_homework', models.FloatField(blank=True, null=True)),
                ('avg_time_spent_homework', models.FloatField(blank=True, null=True)),
                ('median_time_spent_homework', models.FloatField(blank=True, null=True)),
                ('q1_time_spent_homework', models.FloatField(blank=True, null=True)),
                ('q3_time_spent_homework', models.FloatField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='courses.homework')),
            ],
        ),
    ]
