# Generated by Django 5.1.7 on 2025-06-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='problems_comments_field',
        ),
        migrations.AddField(
            model_name='course',
            name='homework_problems_comments_field',
            field=models.BooleanField(default=False, help_text='Include field for problems and comments in homework'),
        ),
    ]
