# Generated by Django 5.2.4 on 2025-07-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_remove_homework_problems_comments_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='points_to_pass',
        ),
        migrations.AddField(
            model_name='course',
            name='project_passing_score',
            field=models.IntegerField(default=0, help_text='Minimum score required to pass any project in this course'),
        ),
    ]
