# Generated by Django 5.2.4 on 2025-08-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_project_points_to_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='min_projects_to_pass',
            field=models.IntegerField(default=1, help_text='The minimum number of projects to pass the course.'),
        ),
    ]
