# Generated by Django 5.2.4 on 2025-09-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_min_projects_to_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.IntegerField(default=0)),
                ('min_project_score', models.IntegerField(blank=True, null=True)),
                ('max_project_score', models.IntegerField(blank=True, null=True)),
                ('avg_project_score', models.FloatField(blank=True, null=True)),
                ('median_project_score', models.FloatField(blank=True, null=True)),
                ('q1_project_score', models.FloatField(blank=True, null=True)),
                ('q3_project_score', models.FloatField(blank=True, null=True)),
                ('min_project_learning_in_public_score', models.IntegerField(blank=True, null=True)),
                ('max_project_learning_in_public_score', models.IntegerField(blank=True, null=True)),
                ('avg_project_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('median_project_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('q1_project_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('q3_project_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('min_peer_review_score', models.IntegerField(blank=True, null=True)),
                ('max_peer_review_score', models.IntegerField(blank=True, null=True)),
                ('avg_peer_review_score', models.FloatField(blank=True, null=True)),
                ('median_peer_review_score', models.FloatField(blank=True, null=True)),
                ('q1_peer_review_score', models.FloatField(blank=True, null=True)),
                ('q3_peer_review_score', models.FloatField(blank=True, null=True)),
                ('min_peer_review_learning_in_public_score', models.IntegerField(blank=True, null=True)),
                ('max_peer_review_learning_in_public_score', models.IntegerField(blank=True, null=True)),
                ('avg_peer_review_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('median_peer_review_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('q1_peer_review_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('q3_peer_review_learning_in_public_score', models.FloatField(blank=True, null=True)),
                ('min_total_score', models.IntegerField(blank=True, null=True)),
                ('max_total_score', models.IntegerField(blank=True, null=True)),
                ('avg_total_score', models.FloatField(blank=True, null=True)),
                ('median_total_score', models.FloatField(blank=True, null=True)),
                ('q1_total_score', models.FloatField(blank=True, null=True)),
                ('q3_total_score', models.FloatField(blank=True, null=True)),
                ('min_time_spent', models.FloatField(blank=True, null=True)),
                ('max_time_spent', models.FloatField(blank=True, null=True)),
                ('avg_time_spent', models.FloatField(blank=True, null=True)),
                ('median_time_spent', models.FloatField(blank=True, null=True)),
                ('q1_time_spent', models.FloatField(blank=True, null=True)),
                ('q3_time_spent', models.FloatField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='courses.project')),
            ],
        ),
    ]
