# Generated by Django 5.2.4 on 2025-10-03 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_projectstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about_content',
            field=models.TextField(blank=True, help_text='Markdown content for the course landing page'),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Hero image URL for the course landing page', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='course',
            name='mailchimp_tag',
            field=models.CharField(blank=True, help_text='Mailchimp tag for newsletter subscriptions', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description for the course landing page'),
        ),
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('RE', 'Registration'), ('AC', 'Active'), ('FI', 'Finished')], default='AC', help_text='Current state of the course (Registration, Active, or Finished)', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube URL for course overview video', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('data_analyst', 'Data Analyst'), ('ml_engineer', 'ML Engineer'), ('software_engineer_backend', 'Software Engineer (Backend)'), ('software_engineer_other', 'Software Engineer (Frontend, Test, etc)'), ('student_stem', 'Student (STEM)'), ('student_non_stem', 'Student (Non-STEM)'), ('other', 'Other')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('mailchimp_subscribed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'unique_together': {('course', 'email')},
            },
        ),
    ]
