# Generated by Django 4.2.14 on 2024-10-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_projectstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, help_text='Whether the course is visible in the course list. Non-visible courses are still accessible via direct link.'),
        ),
    ]
