# Generated by Django 5.2.4 on 2025-10-04 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0019_course_instructor'),
        ('courses', '0022_projectstatistics'),
    ]

    operations = []
