# Generated by Django 5.2.4 on 2025-10-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_course_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('FF', 'Free Form'), ('FL', 'Free Form Long'), ('CB', 'Checkboxes')], max_length=2),
        ),
    ]
