# Generated by Django 5.2.4 on 2025-12-12 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_question_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrappedStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year for which statistics are calculated', unique=True)),
                ('is_visible', models.BooleanField(default=False, help_text='Whether to display this wrapped on the main page')),
                ('total_participants', models.IntegerField(default=0)),
                ('total_enrollments', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('total_certificates', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('course_stats', models.JSONField(default=list, help_text='List of courses with enrollment counts')),
                ('leaderboard', models.JSONField(default=list, help_text='Top 100 users by total score')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wrapped Statistics',
                'verbose_name_plural': 'Wrapped Statistics',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='UserWrappedStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('homework_count', models.IntegerField(default=0)),
                ('project_count', models.IntegerField(default=0)),
                ('peer_reviews_given', models.IntegerField(default=0)),
                ('learning_in_public_count', models.IntegerField(default=0)),
                ('faq_contributions_count', models.IntegerField(default=0)),
                ('certificates_earned', models.IntegerField(default=0)),
                ('courses', models.JSONField(default=list, help_text='List of courses with scores')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_statistics', to=settings.AUTH_USER_MODEL)),
                ('wrapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statistics', to='courses.wrappedstatistics')),
            ],
            options={
                'verbose_name': 'User Wrapped Statistics',
                'verbose_name_plural': 'User Wrapped Statistics',
                'ordering': ['rank'],
                'unique_together': {('wrapped', 'user')},
            },
        ),
    ]
