# Generated by Django 5.2.4 on 2026-01-29 20:27

import courses.validators.criteria_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_add_wrapped_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='disable_learning_in_public',
            field=models.BooleanField(default=False, help_text='When enabled, all learning in public scores are removed and future submissions are not counted', verbose_name='Disable learning in public'),
        ),
        migrations.AlterField(
            model_name='reviewcriteria',
            name='options',
            field=models.JSONField(validators=[courses.validators.criteria_validators.validate_review_criteria_options]),
        ),
    ]
