# Generated by Django 5.2.4 on 2026-05-01 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_enrollment_disable_learning_in_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='instructions_url',
            field=models.URLField(blank=True, help_text='Optional link to the homework instructions.', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AddField(
            model_name='project',
            name='instructions_url',
            field=models.URLField(blank=True, help_text='Optional link to the project instructions.', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
