# Generated by Django 5.2.4 on 2026-05-01 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_merge_instruction_urls_and_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, help_text='The public end date for the course.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Optional external registration page for the course.', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='course',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='Optional GitHub repository URL for the course.', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='The public start date for the course.', null=True),
        ),
    ]
