# Generated by Django 5.2.4 on 2026-05-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_course_end_date_course_registration_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='faq_contribution_url',
            field=models.URLField(blank=True, help_text='Pull request or issue URL for the FAQ contribution', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='faq_contribution_url',
            field=models.URLField(blank=True, help_text='Pull request or issue URL for the FAQ contribution', null=True),
        ),
    ]
