# Generated by Django 5.2.4 on 2026-06-07 09:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_projectsubmission_volunteer_review_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('edition_label', models.CharField(blank=True, help_text="Displayed cohort label, for example '2026 cohort'.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('marketing_markdown', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('video_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('mailchimp_tag_before_switch', models.CharField(blank=True, max_length=100)),
                ('mailchimp_tag_after_switch', models.CharField(blank=True, max_length=100)),
                ('mailchimp_tag_switch_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_course', models.ForeignKey(blank=True, help_text='Course edition currently promoted by this form.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_campaigns', to='courses.course')),
            ],
            options={
                'ordering': ['title', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_normalized', models.EmailField(editable=False, max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('data_analyst', 'Data Analyst'), ('ml_engineer', 'ML Engineer'), ('software_engineer_backend', 'Software Engineer (Backend)'), ('software_engineer_other', 'Software Engineer (Frontend, Test, etc)'), ('student_stem', 'Student (STEM)'), ('student_non_stem', 'Student (Non-STEM)'), ('other', 'Other')], max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('accepted_newsletter', models.BooleanField(default=False)),
                ('mailchimp_sync_status', models.CharField(choices=[('skipped', 'Skipped'), ('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mailchimp_tag_used', models.CharField(blank=True, max_length=100)),
                ('mailchimp_synced_at', models.DateTimeField(blank=True, null=True)),
                ('mailchimp_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_registrations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.registrationcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'email_normalized')},
            },
        ),
    ]
