# Generated by Django 5.2.4 on 2026-06-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_registrationcampaign_courseregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='mailchimp_sync_status',
            field=models.CharField(choices=[('skipped', 'Skipped'), ('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='skipped', max_length=20),
        ),
    ]
