# Generated by Django 5.2.4 on 2026-06-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_courseregistration_mailchimp_sync_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='mailchimp_error',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='mailchimp_sync_status',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='mailchimp_synced_at',
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='mailchimp_tag_used',
        ),
        migrations.RemoveField(
            model_name='registrationcampaign',
            name='mailchimp_tag_after_switch',
        ),
        migrations.RemoveField(
            model_name='registrationcampaign',
            name='mailchimp_tag_before_switch',
        ),
        migrations.RemoveField(
            model_name='registrationcampaign',
            name='mailchimp_tag_switch_at',
        ),
    ]
