# Generated by Django 5.2.4 on 2026-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_remove_courseregistration_mailchimp_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseregistration",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
