# Generated by Django 5.2.4 on 2026-08-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_system_project_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcampaign',
            name='email_body_markdown',
            field=models.TextField(blank=True, help_text='Overrides marketing_markdown as the Datamailer email body. Leave blank to reuse the landing-page copy.'),
        ),
    ]
