# Generated by Django 5.2.4 on 2026-08-31 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_registrationcampaign_email_body_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcampaign',
            name='email_body_markdown',
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('body_markdown', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('synced', 'Synced'), ('queued', 'Queued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('external_key', models.CharField(editable=False, max_length=100, unique=True)),
                ('last_recipient_count', models.PositiveIntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='courses.registrationcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
