# Generated by Django 5.2.4 on 2026-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_remove_registrationcampaign_email_body_markdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('synced', 'Synced'), ('queue_pending', 'Queue Pending'), ('queued', 'Queued'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
