# Country and region data
COUNTRIES = [
    ("Algeria", "Africa"),
    ("Angola", "Africa"),
    ("Benin", "Africa"),
    ("Botswana", "Africa"),
    ("Burkina Faso", "Africa"),
    ("Burundi", "Africa"),
    ("Cabo Verde", "Africa"),
    ("Cameroon", "Africa"),
    ("Central African Republic", "Africa"),
    ("Chad", "Africa"),
    ("Comoros", "Africa"),
    ("Congo", "Africa"),
    ("Democratic Republic of the Congo", "Africa"),
    ("Cote d'Ivoire", "Africa"),
    ("Djibouti", "Africa"),
    ("Egypt", "Africa"),
    ("Equatorial Guinea", "Africa"),
    ("Eritrea", "Africa"),
    ("Eswatini", "Africa"),
    ("Ethiopia", "Africa"),
    ("Gabon", "Africa"),
    ("Gambia", "Africa"),
    ("Ghana", "Africa"),
    ("Guinea", "Africa"),
    ("Guinea-Bissau", "Africa"),
    ("Kenya", "Africa"),
    ("Lesotho", "Africa"),
    ("Liberia", "Africa"),
    ("Libya", "Africa"),
    ("Madagascar", "Africa"),
    ("Malawi", "Africa"),
    ("Mali", "Africa"),
    ("Mauritania", "Africa"),
    ("Mauritius", "Africa"),
    ("Morocco", "Africa"),
    ("Mozambique", "Africa"),
    ("Namibia", "Africa"),
    ("Niger", "Africa"),
    ("Nigeria", "Africa"),
    ("Rwanda", "Africa"),
    ("Sao Tome and Principe", "Africa"),
    ("Senegal", "Africa"),
    ("Seychelles", "Africa"),
    ("Sierra Leone", "Africa"),
    ("Somalia", "Africa"),
    ("South Africa", "Africa"),
    ("South Sudan", "Africa"),
    ("Sudan", "Africa"),
    ("Tanzania", "Africa"),
    ("Togo", "Africa"),
    ("Tunisia", "Africa"),
    ("Uganda", "Africa"),
    ("Zambia", "Africa"),
    ("Zimbabwe", "Africa"),
    ("Canada", "North America"),
    ("United States", "North America"),
    ("United States of America", "North America"),
    ("Mexico", "North America"),
    ("Bermuda", "North America"),
    ("Greenland", "North America"),
    ("Saint Pierre and Miquelon", "North America"),
    ("Belize", "North America"),
    ("Costa Rica", "North America"),
    ("El Salvador", "North America"),
    ("Guatemala", "North America"),
    ("Honduras", "North America"),
    ("Nicaragua", "North America"),
    ("Panama", "North America"),
    ("Cuba", "North America"),
    ("Dominican Republic", "North America"),
    ("Haiti", "North America"),
    ("Jamaica", "North America"),
    ("Trinidad and Tobago", "North America"),
    ("Barbados", "North America"),
    ("Bahamas", "North America"),
    ("Grenada", "North America"),
    ("Saint Lucia", "North America"),
    ("Saint Vincent and the Grenadines", "North America"),
    ("Dominica", "North America"),
    ("Antigua and Barbuda", "North America"),
    ("Saint Kitts and Nevis", "North America"),
    ("Puerto Rico", "North America"),
    ("Curacao", "North America"),
    ("Aruba", "North America"),
    ("Cayman Islands", "North America"),
    ("Argentina", "South America"),
    ("Bolivia", "South America"),
    ("Brazil", "South America"),
    ("Chile", "South America"),
    ("Colombia", "South America"),
    ("Ecuador", "South America"),
    ("Guyana", "South America"),
    ("Paraguay", "South America"),
    ("Peru", "South America"),
    ("Suriname", "South America"),
    ("Uruguay", "South America"),
    ("Venezuela", "South America"),
    ("French Guiana", "South America"),
    ("Falkland Islands", "South America"),
    ("Afghanistan", "Asia"),
    ("Armenia", "Asia"),
    ("Azerbaijan", "Asia"),
    ("Bahrain", "Asia"),
    ("Bangladesh", "Asia"),
    ("Bhutan", "Asia"),
    ("Brunei", "Asia"),
    ("Cambodia", "Asia"),
    ("China", "Asia"),
    ("Georgia", "Asia"),
    ("India", "Asia"),
    ("Indonesia", "Asia"),
    ("Iran", "Asia"),
    ("Iraq", "Asia"),
    ("Israel", "Asia"),
    ("Japan", "Asia"),
    ("Jordan", "Asia"),
    ("Kazakhstan", "Asia"),
    ("Kuwait", "Asia"),
    ("Kyrgyzstan", "Asia"),
    ("Laos", "Asia"),
    ("Lebanon", "Asia"),
    ("Malaysia", "Asia"),
    ("Maldives", "Asia"),
    ("Mongolia", "Asia"),
    ("Myanmar", "Asia"),
    ("Nepal", "Asia"),
    ("North Korea", "Asia"),
    ("Oman", "Asia"),
    ("Pakistan", "Asia"),
    ("Palestine", "Asia"),
    ("Philippines", "Asia"),
    ("Qatar", "Asia"),
    ("Saudi Arabia", "Asia"),
    ("Singapore", "Asia"),
    ("South Korea", "Asia"),
    ("Sri Lanka", "Asia"),
    ("Syria", "Asia"),
    ("Tajikistan", "Asia"),
    ("Thailand", "Asia"),
    ("Timor-Leste", "Asia"),
    ("Turkey", "Asia"),
    ("Turkmenistan", "Asia"),
    ("United Arab Emirates", "Asia"),
    ("Uzbekistan", "Asia"),
    ("Vietnam", "Asia"),
    ("Yemen", "Asia"),
    ("Albania", "Europe"),
    ("Andorra", "Europe"),
    ("Austria", "Europe"),
    ("Belarus", "Europe"),
    ("Belgium", "Europe"),
    ("Bosnia and Herzegovina", "Europe"),
    ("Bulgaria", "Europe"),
    ("Croatia", "Europe"),
    ("Cyprus", "Europe"),
    ("Czechia", "Europe"),
    ("Denmark", "Europe"),
    ("Estonia", "Europe"),
    ("Finland", "Europe"),
    ("France", "Europe"),
    ("Germany", "Europe"),
    ("Greece", "Europe"),
    ("Hungary", "Europe"),
    ("Iceland", "Europe"),
    ("Ireland", "Europe"),
    ("Italy", "Europe"),
    ("Kosovo", "Europe"),
    ("Latvia", "Europe"),
    ("Liechtenstein", "Europe"),
    ("Lithuania", "Europe"),
    ("Luxembourg", "Europe"),
    ("Malta", "Europe"),
    ("Moldova", "Europe"),
    ("Monaco", "Europe"),
    ("Montenegro", "Europe"),
    ("Netherlands", "Europe"),
    ("North Macedonia", "Europe"),
    ("Norway", "Europe"),
    ("Poland", "Europe"),
    ("Portugal", "Europe"),
    ("Romania", "Europe"),
    ("Russia", "Europe"),
    ("San Marino", "Europe"),
    ("Serbia", "Europe"),
    ("Slovakia", "Europe"),
    ("Slovenia", "Europe"),
    ("Spain", "Europe"),
    ("Sweden", "Europe"),
    ("Switzerland", "Europe"),
    ("Ukraine", "Europe"),
    ("United Kingdom", "Europe"),
    ("Vatican City", "Europe"),
    ("Australia", "Oceania"),
    ("New Zealand", "Oceania"),
    ("Fiji", "Oceania"),
    ("Papua New Guinea", "Oceania"),
    ("Solomon Islands", "Oceania"),
    ("Vanuatu", "Oceania"),
    ("Samoa", "Oceania"),
    ("Tonga", "Oceania"),
    ("Kiribati", "Oceania"),
    ("Tuvalu", "Oceania"),
    ("Nauru", "Oceania"),
    ("Micronesia", "Oceania"),
    ("Palau", "Oceania"),
    ("Marshall Islands", "Oceania"),
    ("New Caledonia", "Oceania"),
]

# Role choices for registration
ROLE_CHOICES = [
    ("data_engineer", "Data Engineer"),
    ("data_scientist", "Data Scientist"),
    ("data_analyst", "Data Analyst"),
    ("ml_engineer", "ML Engineer"),
    ("software_engineer_backend", "Software Engineer (Backend)"),
    ("software_engineer_other", "Software Engineer (Frontend, Test, etc)"),
    ("student_stem", "Student (STEM)"),
    ("student_non_stem", "Student (Non-STEM)"),
    ("other", "Other"),
]

# Course state choices
class CourseState:
    REGISTRATION = "RE"
    ACTIVE = "AC"
    FINISHED = "FI"
    
    CHOICES = [
        (REGISTRATION, "Registration"),
        (ACTIVE, "Active"),
        (FINISHED, "Finished"),
    ]
